#' @title RRA interactions
#' @description Rank interactions based on CellChat, LIANA (use all methods), cell2cell and CellPhoneDB
#' @param cellchat_obj path to file generated by 'format_cellchat()'
#' @param liana_obj path to file generated by 'format_liana()'
#' @param cell2cell_obj path to file generated by 'format_cell2cell()'
#' @param cpdb_obj path to file generated by 'format_cpdb()'
#' @param output_dir output directory for saving output (default = '.')
#' @param sample_id sample id to use for saving object
#' @param alpha significance threshold (default = 0.05)
#' @importFrom dplyr %>%
#' @export
take_consensus <- function(
    cellchat_obj, liana_obj, cell2cell_obj, cpdb_obj,
    sample_id = NULL, output_dir = ".", alpha = 0.05) {
    #  Sanity checks
    if (!(file.exists(cellchat_obj) && endsWith(cellchat_obj, ".rds"))) {
        stop(glue::glue("'{cellchat_obj}' does not exists or is not an RDS object"))
    }
    if (!(file.exists(liana_obj) && endsWith(liana_obj, ".rds"))) {
        stop(glue::glue("'{liana_obj}' does not exists or is not an RDS object"))
    }
    if (!(file.exists(cell2cell_obj) && endsWith(cell2cell_obj, ".rds"))) {
        stop(glue::glue("'{cell2cell_obj}' does not exists or is not an RDS object"))
    }
    if (!(file.exists(cpdb_obj) && endsWith(cpdb_obj, ".rds"))) {
        stop(glue::glue("'{cpdb_obj}' does not exists or is not an RDS object"))
    }
    if (!file.exists(output_dir)) {
        stop("Output directory does not exist")
    }
    if (is.null(sample_id)) {
        stop("No sample_id given")
    }

    message("Load postprocessed objects from CCIs...")
    # Pre-filtering on p-value, only impacts when downsampling is done (pval == NA, if interaction not detected in each downsampling run)
    obj_cellchat <- readRDS(cellchat_obj)
    obj_liana <- readRDS(liana_obj)
    obj_cell2cell <- readRDS(cellchat_obj)
    obj_cpdb <- readRDS(cpdb_obj)
    common_cols <- c("source_target", "complex_interaction", "pval", "method", "Sample")

    message(glue::glue("Filter by significance... (alpha = {alpha})"))
    obj_cellchat_filtered <- obj_cellchat %>%
        dplyr::select(dplyr::all_of(common_cols)) %>%
        filter(!is.na(pval)) %>%
        filter(pval < alpha) %>%
        dplyr::select(-pval)
    # r$> head(obj_cellchat)
    #                 source_target complex_interaction     method                Sample
    # 1        Malignant__Malignant COL4A2__ITGAV:ITGB8 CellChatv2 6514_enhancing_border
    # 2  Oligodendrocyte__Malignant COL4A5__ITGAV:ITGB8 CellChatv2 6514_enhancing_border
    # 3      Macrophage__Macrophage   SPP1__ITGAV:ITGB1 CellChatv2 6514_enhancing_border
    # 4       Microglia__Macrophage   SPP1__ITGAV:ITGB1 CellChatv2 6514_enhancing_border
    # 5 Oligodendrocyte__Macrophage   SPP1__ITGAV:ITGB1 CellChatv2 6514_enhancing_border
    # 6        Malignant__Malignant   GLS:SLC1A2__GRIA2 CellChatv2 6514_enhancing_border
    obj_liana_filtered <- obj_liana %>%
        dplyr::select(dplyr::all_of(common_cols)) %>%
        filter(!is.na(pval)) %>%
        filter(pval < alpha) %>%
        dplyr::select(-pval)
    # r$> head(obj_liana)
    # # A tibble: 6 × 4
    #   source_target                    complex_interaction method Sample
    #   <chr>                            <chr>               <chr>  <chr>
    # 1 Oligodendrocyte__Oligodendrocyte CNTN2__CNTN2        LIANA  6514_enhancing_border
    # 2 Malignant__Malignant             BCAN__EGFR          LIANA  6514_enhancing_border
    # 3 Oligodendrocyte__Oligodendrocyte CLDN11__CLDN11      LIANA  6514_enhancing_border
    # 4 Malignant__Malignant             BCAN__NRCAM         LIANA  6514_enhancing_border
    # 5 Oligodendrocyte__Oligodendrocyte TF__LRP2            LIANA  6514_enhancing_border
    # 6 Malignant__Malignant             CHL1__CHL1          LIANA  6514_enhancing_border
    obj_cell2cell_filtered <- obj_cell2cell %>%
        dplyr::select(dplyr::all_of(common_cols)) %>%
        filter(!is.na(pval)) %>%
        filter(pval < alpha) %>%
        dplyr::select(-pval)
    # r$> head(obj_cell2cell)
    #           source_target  complex_interaction    method                Sample
    # 1 Macrophage__Malignant    NRG2__ERBB2:ERBB3 Cell2Cell 6514_enhancing_border
    # 2 Macrophage__Malignant    NRG2__ERBB2:ERBB4 Cell2Cell 6514_enhancing_border
    # 3 Macrophage__Malignant     EREG__EGFR:ERBB2 Cell2Cell 6514_enhancing_border
    # 4 Macrophage__Malignant    EREG__ERBB2:ERBB4 Cell2Cell 6514_enhancing_border
    # 5 Macrophage__Malignant NFASC__CNTN1:CNTNAP1 Cell2Cell 6514_enhancing_border
    # 6 Macrophage__Malignant    THY1__ITGAM:ITGB2 Cell2Cell 6514_enhancing_border
    obj_cpdb_filtered <- obj_cpdb %>%
        dplyr::select(dplyr::all_of(common_cols)) %>%
        filter(!is.na(pval)) %>%
        filter(pval < alpha) %>%
        dplyr::select(-pval)
    # r$> head(obj_cpdb)
    #            source_target complex_interaction        method                Sample
    # 1 Macrophage__Macrophage        TGFB1__ITGB1 CellPhoneDBv5 6514_enhancing_border
    # 2 Macrophage__Macrophage         SPP1__ITGB1 CellPhoneDBv5 6514_enhancing_border
    # 3 Macrophage__Macrophage         CD14__ITGB1 CellPhoneDBv5 6514_enhancing_border
    # 4 Macrophage__Macrophage       ADAM17__ITGB1 CellPhoneDBv5 6514_enhancing_border
    # 5 Macrophage__Macrophage        ADAM9__ITGB1 CellPhoneDBv5 6514_enhancing_border
    # 6 Macrophage__Macrophage       LGALS1__ITGB1 CellPhoneDBv5 6514_enhancing_border

    message(glue::glue("Number of interactions in CellChat AFTER filtering: {nrow(obj_cellchat_filtered)}"))
    message(glue::glue("Number of interactions in LIANA AFTER filtering: {nrow(obj_liana_filtered)}"))
    message(glue::glue("Number of interactions in Cell2Cell AFTER filtering: {nrow(obj_cell2cell_filtered)}"))
    message(glue::glue("Number of interactions in CPDB AFTER filtering: {nrow(obj_cpdb_filtered)}"))

    message("Combine the different methods...")
    interactions_signif <- do.call(rbind, list(
        obj_cellchat_filtered,
        obj_liana_filtered,
        obj_cell2cell_filtered,
        obj_cpdb_filtered
    ))
    # r$> head(interactions_signif)
    #                 source_target complex_interaction     method                Sample
    # 1        Malignant__Malignant COL4A2__ITGAV:ITGB8 CellChatv2 6514_enhancing_border
    # 2  Oligodendrocyte__Malignant COL4A5__ITGAV:ITGB8 CellChatv2 6514_enhancing_border
    # 3      Macrophage__Macrophage   SPP1__ITGAV:ITGB1 CellChatv2 6514_enhancing_border
    # 4       Microglia__Macrophage   SPP1__ITGAV:ITGB1 CellChatv2 6514_enhancing_border
    # 5 Oligodendrocyte__Macrophage   SPP1__ITGAV:ITGB1 CellChatv2 6514_enhancing_border
    # 6        Malignant__Malignant   GLS:SLC1A2__GRIA2 CellChatv2 6514_enhancing_border

    message(glue::glue("Number of interactions: {nrow(interactions_signif)}"))
    utils::capture.output(print(head(interactions_signif)))
    # Remove duplicates
    interactions_signif <- interactions_signif %>%
        dplyr::distinct()
    message(glue::glue("After filtering: {nrow(interactions_signif)}"))

    # Number of votes per interaction per source-target per Sample (i.e. detected in how many methods)
    cols_oi <- c("Sample", "source_target", "complex_interaction")
    all_votes <- interactions_signif %>%
        dplyr::group_by(Sample, source_target, complex_interaction) %>%
        dplyr::count() %>%
        dplyr::rename(n_methods = n) %>%
        # Adding scores regardless of pval
        dplyr::left_join(obj_liana %>% dplyr::select(dplyr::all_of(cols_oi), LIANA_score)) %>%
        dplyr::left_join(obj_cellchat %>% dplyr::select(dplyr::all_of(cols_oi), CellChat_score)) %>%
        dplyr::left_join(obj_cell2cell %>% dplyr::select(dplyr::all_of(cols_oi))) %>%
        dplyr::left_join(obj_cpdb %>% dplyr::select(dplyr::all_of(cols_oi), CellPhoneDB_score)) %>%
        # Adding binary info on whether interaction was found significant in individual methods
        dplyr::left_join(obj_liana %>% filter(pval < alpha) %>% dplyr::select(dplyr::all_of(cols_oi)) %>% dplyr::mutate(in_liana = 1)) %>%
        dplyr::left_join(obj_cellchat %>% filter(pval < alpha) %>% dplyr::select(dplyr::all_of(cols_oi)) %>% dplyr::mutate(in_cellchat = 1)) %>%
        dplyr::left_join(obj_cell2cell %>% filter(pval < alpha) %>% dplyr::select(dplyr::all_of(cols_oi)) %>% dplyr::mutate(in_cell2cell = 1)) %>%
        dplyr::left_join(obj_cpdb %>% filter(pval < alpha) %>% dplyr::select(dplyr::all_of(cols_oi)) %>% dplyr::mutate(in_cpdb = 1))
    all_votes[is.na(all_votes)] <- 0

    message("Take consensus...")
    # TODO we could change this if necessary
    interactions_mvoted <- all_votes %>%
        dplyr::group_by(Sample, source_target, complex_interaction) %>%
        dplyr::mutate(
            lenient_voting = (n_methods >= 3) & (in_liana == 1),
            stringent_voting = (n_methods == 4)
        )

    message(glue::glue("Number of interactions after consensus: {nrow(interactions_mvoted)}"))

    message("Save output...")
    saveRDS(
        interactions_mvoted,
        glue::glue("{output_dir}/{sample_id}__interactions_mvoted.rds")
    )
    saveRDS(
        all_votes,
        glue::glue("{output_dir}/{sample_id}__signif_interactions.rds")
    )
}
