#' @title Format cell2cell CCI results
#' @param input_interactions path to file with the inferred interactions from cell2cell (output file generated by Python/202_cci_cell2cell.py, a csv file)
#' @param output_dir output directory for saving output (default = '.')
#' @param sample_id sample id to use for saving formatted CCI results (default = NULL; will determine sample id based on 'input_interactions' for this input_interactions has to be of the format 'cell2cell__{sample_id}.csv')
#' @export
format_cell2cell <- function(input_interactions, output_dir = ".", sample_id = NULL) {
    #  Sanity checks
    if (!(file.exists(input_interactions) && endsWith(input_interactions, ".csv"))) {
        stop("Interactions file ('input_interactions') does not exists or is not an csv file")
    }
    if (!file.exists(output_dir)) {
        stop("Output directory does not exist")
    }

    if (is.null(sample_id)) {
        # Setting sample + run id depending on downsampling or not
        split_sample_id <- stringr::str_split(sample_id, "__", simplify = TRUE)
        sample_id <- split_sample_id[1]
    }
    message(glue::glue("Formatting sample={sample_id}..."))

    message("Load interactions...")
    interactions <- data.frame(data.table::fread(input_interactions, header = TRUE, sep = "\t"),
        check.names = FALSE
    )
    message("Formatting results...")
    interactions <- interactions %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
            interaction = V1 %>% stringr::str_replace_all("\\(|,|\\'|\\)", "") %>%
                stringr::str_replace_all(" ", "_")
        ) %>%
        dplyr::ungroup() %>%
        dplyr::select(-V1) %>%
        reshape2::melt(
            id.vars = c("interaction"),
            variable.name = "source_target",
            value.name = "pval"
        ) %>%
        dplyr::mutate(
            source_target = stringr::str_replace_all(source_target, ";", "__"),
            method = "Cell2Cell",
            Sample = sample_id
        ) %>%
        dplyr::select(-interaction)

    message("Save output...")
    saveRDS(interactions,
        file = glue::glue("{output_dir}/cell2cell__{sample}__postproc.rds")
    )

    message("Finished!")
}
