#' @title Format cell2cell CCI results
#' @param c2c_df dataframe with the inferred interactions from cell2cell (output file generated by Python/202_cci_cell2cell.py, a csv file)
#' @param mode 'pval' or 'interaction_score' dependent on input
#' @return dataframe with columns: interaction, source_target, pval
#' @export
format_cell2cell <- function(
    c2c_df,
    mode = c("pval", "interaction_score")[1]
) {
    match.arg(mode, c("pval", "interaction_score"))

    return(
        c2c_df |>
            dplyr::rename(interaction = V1) |>
            tidyr::pivot_longer(
                cols = !interaction,
                names_to = "source_target",
                values_to = mode
            ) |>
            duckplyr::as_duckdb_tibble() |>
            dplyr::mutate(
                interaction = stringr::str_replace_all(
                    interaction,
                    "\\(|,|\\'|\\)",
                    ""
                ) |>
                    stringr::str_replace_all(string = _, " ", "_"),
                source_target = stringr::str_replace_all(
                    source_target,
                    ";",
                    "__"
                )
            )
    )
}

#' @title Format cell2cell CCI results
#' @param input_interactions_pval dataframe with the inferred interactions pvalues from cell2cell (output file generated by Python/202_cci_cell2cell.py, a csv file)
#' @param input_interactions_scores dataframe with the inferred interactions pvalues from cell2cell (output file generated by Python/202_cci_cell2cell.py, a csv file)
#' @param ref_db dataframe with reference database of interactions
#' @param sample_id character string for sample_id to add to dataframe (if non given set to NA)
#' @return dataframe with columns: source_target, pval, interaction_score, complex_interaction, method, sample_id
#' @export
format_cell2cell_wrapper <- function(
    input_interactions_pval,
    input_interactions_scores,
    ref_db,
    sample_id = NA
) {
    df <- purrr::map2(
        list(input_interactions_pval, input_interactions_scores),
        c("pval", "interaction_score"),
        format_cell2cell
    ) |>
        purrr::reduce(full_join, by = c("source_target", "interaction")) |>
        dplyr::left_join(ref_db, by = "interaction") |>
        dplyr::select(-interaction) |>
        dplyr::mutate(
            method = "Cell2Cell",
            sample_id = !!sample_id
        )

    message("Finished!")
    return(df)
}
