#' @title Format LIANA CCI results
#' @param cci_obj LIANA object with the inferred interactions, generated by run_LIANA()
#' @param sample_id character string for sample_id to add to dataframe (if non given set to NA)
#' @param ref_db dataframe with reference database of interactions
#' @return dataframe
#' @export
format_liana <- function(
    cci_obj,
    ref_db,
    sample_id = NA
) {
    df <- cci_obj |>
        liana::liana_aggregate() |>
        duckplyr::as_duckdb_tibble() |>
        dplyr::rename(
            pval = aggregate_rank
        ) |>
        dplyr::mutate(interaction_score = sca.LRscore) |>
        tidyr::unite(
            interaction,
            ligand.complex,
            receptor.complex,
            sep = "_"
        ) |>
        duckplyr::as_duckdb_tibble() |>
        dplyr::left_join(ref_db, by = "interaction") |>
        # Needed for aggregating/combining the CCI data from different tools & samples
        dplyr::mutate(method = "LIANA", sample_id = !!sample_id) |>
        dplyr::select(-interaction) |>
        tidyr::unite(source_target, source, target, sep = "__")

    message("Finished!")
    return(df)
}
