#' @title Format LIANA CCI results
#' @param input_interactions path to file with the inferred interactions from LIANA (output file generated by run_LIANA()) (rds file)
#' @param output_dir output directory for saving output (default = '.')
#' @param sample_id sample id to use for saving formatted CCI results (default = NULL; will determine sample id based on 'input_interactions' for this input_interactions has to be of the format 'LIANA__{sample_id}.rds')
#' @export
#' @importFrom dplyr %>%
format_liana <- function(input_interactions, output_dir = ".", sample_id = NULL) {
    #  Sanity checks
    if (!(file.exists(input_interactions) && endsWith(input_interactions, ".rds"))) {
        stop("Interactions file ('input_interactions') does not exists or is not an RDS object")
    }
    if (!file.exists(output_dir)) {
        stop("Output directory does not exist")
    }
    message("Load data...")
    interactions <- readRDS(input_interactions)

    if (is.null(sample_id)) {
        # Setting sample + run id depending on downsampling or not
        split_sample_id <- stringr::str_split(sample_id, "__", simplify = TRUE)
        sample_id <- split_sample_id[1]
    }

    message(glue::glue("Formatting sample={sample_id}..."))
    # FIX temporary solution of bug cytotalk (duplicate interactions)
    # interactions$cytotalk <- interactions$cytotalk %>% dplyr::distinct(source, target, ligand.complex, receptor.complex, .keep_all = TRUE)

    interactions <- interactions %>%
        liana::liana_aggregate() %>%
        dplyr::rename(
            pval = aggregate_rank
        ) %>%
        dplyr::mutate(LIANA_score = sca.LRscore) %>%
        # select(source, target, ligand.complex, receptor.complex, pval, interaction_score) %>%
        tidyr::unite(interaction, ligand.complex, receptor.complex, sep = "_") %>%
        tidyr::unite(source_target, source, target, sep = "__") %>%
        dplyr::mutate(method = "LIANA", Sample = sample_id)

    message("Save output...")
    saveRDS(interactions, glue::glue("{output_dir}/liana__{sample_id}__postproc.rds"))
    message("Finished!")
}
