#' @title Format cell2cell CCI results
#' @param input_interactions path to file with the inferred interactions from cell2cell (output file generated by Python/202_cci_cell2cell.py, a csv file)
#' @param output_dir output directory for saving output (default = '.')
#' @param sample_id sample id to use for saving formatted CCI results (default = NULL; will determine sample id based on 'input_interactions' for this input_interactions has to be of the format 'cell2cell__{sample_id}.csv')
#' @param ref_db Path to interactions database (default = "data/interactions_db/ref_db.rds")
#' @param mode 'pval' or 'Cell2Cell_score' dependent on input
#' @export
format_cell2cell <- function(
    input_interactions,
    ref_db = "data/interactions_db/ref_db.rds",
    output_dir = ".",
    sample_id = NULL,
    mode = "pval") {
    #  Sanity checks
    if (
        !(file.exists(input_interactions) &&
            endsWith(tolower(input_interactions), ".csv"))
    ) {
        stop(
            "Interactions file ('input_interactions') does not exists or is not an csv file"
        )
    }
    # TODO in future release remove, when switching to new database
    if (!file.exists(ref_db) && endsWith(tolower(input_interactions), ".rds")) {
        stop(glue::glue("{ref_db} path does not exist"))
    }

    if (!file.exists(output_dir)) {
        stop("Output directory does not exist")
    }

    if (is.null(sample_id)) {
        # Setting sample + run id depending on downsampling or not
        split_sample_id <- stringr::str_split(sample_id, "__", simplify = TRUE)
        sample_id <- split_sample_id[1]
    }
    message("Load database...")
    # TODO in future release remove, when switching to new database
    ref_db <- readRDS(ref_db) %>%
        dplyr::select(
            # simple_interaction,
            complex_interaction,
            interaction
        )
    message(glue::glue("Formatting sample={sample_id}..."))

    message("Load interactions...")
    interactions <- data.frame(
        data.table::fread(input_interactions, header = TRUE, sep = "\t"),
        check.names = FALSE
    )
    message("Formatting results...")
    interactions <- interactions %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
            interaction = V1 %>%
                stringr::str_replace_all("\\(|,|\\'|\\)", "") %>%
                stringr::str_replace_all(" ", "_")
        ) %>%
        dplyr::ungroup() %>%
        dplyr::select(-V1) %>%
        reshape2::melt(
            id.vars = c("interaction"),
            variable.name = "source_target",
            value.name = mode
        ) %>%
        dplyr::mutate(
            source_target = stringr::str_replace_all(source_target, ";", "__"),
            method = "Cell2Cell",
            Sample = sample_id
        ) %>%
        dplyr::left_join(ref_db, by = "interaction") %>%
        dplyr::select(-interaction)

    message("Finished!")
    return(interactions)
}

#' @title Format cell2cell CCI results
#' @param input_interactions_pval path to file with the inferred interactions pvalues from cell2cell (output file generated by Python/202_cci_cell2cell.py, a csv file)
#' @param input_interactions_scores path to file with the inferred interactions pvalues from cell2cell (output file generated by Python/202_cci_cell2cell.py, a csv file)
#' @param output_dir output directory for saving output (default = '.')
#' @param sample_id sample id to use for saving formatted CCI results (default = NULL; will determine sample id based on 'input_interactions' for this input_interactions has to be of the format 'cell2cell__{sample_id}.csv')
#' @param ref_db Path to interactions database (default = "data/interactions_db/ref_db.rds")
#' @export
format_cell2cell_wrapper <- function(
    input_interactions_pval,
    input_interactions_scores,
    ref_db = "data/interactions_db/ref_db.rds",
    output_dir = ".",
    sample_id = NULL) {
    message("Formatting p-values output...")
    pval_formatted <- format_cell2cell(
        input_interactions = input_interactions_pval,
        sample_id = sample_id,
        ref_db = ref_db,
        mode = "pval"
    )
    message("Formatting scores output...")
    interaction_scores_formatted <- format_cell2cell(
        input_interactions = input_interactions_scores,
        sample_id = sample_id,
        ref_db = ref_db,
        mode = "Cell2Cell_score"
    )
    message("Combine p-values and scores into a single dataframe...")
    interactions <- merge(interaction_scores_formatted, pval_formatted)

    message("Save output...")
    saveRDS(
        interactions,
        file = glue::glue("{output_dir}/cell2cell__{sample_id}__postproc.rds")
    )

    message("Finished!")
}
