#' @title RRA interactions
#' @description Rank interactions based on CellChat, LIANA (use all methods), cell2cell and CellPhoneDB
#' @param cellchat_obj path to file generated by 'format_cellchat()'
#' @param liana_obj path to file generated by 'format_liana()'
#' @param cell2cell_obj path to file generated by 'format_cell2cell()'
#' @param cpdb_obj path to file generated by 'format_cpdb()'
#' @param output_dir output directory for saving output (default = '.')
#' @param sample_id sample id to use for saving object
#' @importFrom dplyr %>%
#' @export
rra_interactions <- function(
    cellchat_obj, liana_obj, cell2cell_obj, cpdb_obj,
    sample_id = NULL, output_dir = ".") {
    #  Sanity checks
    if (!(file.exists(cellchat_obj) && endsWith(cellchat_obj, ".rds"))) {
        stop(glue::glue("'{cellchat_obj}' does not exists or is not an RDS object"))
    }
    if (!(file.exists(liana_obj) && endsWith(liana_obj, ".rds"))) {
        stop(glue::glue("'{liana_obj}' does not exists or is not an RDS object"))
    }
    if (!(file.exists(cell2cell_obj) && endsWith(cell2cell_obj, ".rds"))) {
        stop(glue::glue("'{cell2cell_obj}' does not exists or is not an RDS object"))
    }
    if (!(file.exists(cpdb_obj) && endsWith(cpdb_obj, ".rds"))) {
        stop(glue::glue("'{cpdb_obj}' does not exists or is not an RDS object"))
    }
    if (!file.exists(output_dir)) {
        stop("Output directory does not exist")
    }
    if (is.null(sample_id)) {
        stop("No sample_id given")
    }

    message("Load postprocessed objects from CCIs...")
    # Pre-filtering on p-value, only impacts when downsampling is done (pval == NA, if interaction not detected in each downsampling run)
    obj_cellchat <- readRDS(cellchat_obj)
    obj_liana <- readRDS(liana_obj)
    obj_cell2cell <- readRDS(cellchat_obj)
    obj_cpdb <- readRDS(cpdb_obj)

    message(glue::glue("Number of interactions in CellChat BEFORE filtering: {nrow(obj_cellchat)}"))
    message(glue::glue("Number of interactions in LIANA BEFORE filtering: {nrow(obj_liana)}"))
    message(glue::glue("Number of interactions in Cell2Cell BEFORE filtering: {nrow(obj_cell2cell)}"))
    message(glue::glue("Number of interactions in CPDB BEFORE filtering: {nrow(obj_cpdb)}"))

    # ---- Order from most-important (significant) to least based on interaction
    # Sorting by score/specificity (NOT p-value)
    connectome <- obj_liana %>%
        dplyr::select(source_target, complex_interaction, Sample, connectome.weight_sc) %>%
        dplyr::mutate(method = "Connectome (LIANA)") %>%
        dplyr::rename(score = connectome.weight_sc) %>%
        dplyr::group_by(Sample, source_target, ) %>%
        dplyr::arrange(Sample, source_target, dplyr::desc(score), .by_group = TRUE)

    logfc <- obj_liana %>%
        dplyr::select(source_target, complex_interaction, Sample, logfc.logfc_comb) %>%
        dplyr::mutate(method = "LogFC (LIANA)") %>%
        dplyr::rename(score = logfc.logfc_comb) %>%
        dplyr::group_by(Sample, source_target, ) %>%
        dplyr::arrange(Sample, source_target, dplyr::desc(score), .by_group = TRUE)

    natmi <- obj_liana %>%
        dplyr::select(source_target, complex_interaction, Sample, natmi.edge_specificity) %>%
        dplyr::mutate(method = "NATMI (LIANA)") %>%
        dplyr::rename(score = natmi.edge_specificity) %>%
        dplyr::group_by(Sample, source_target, ) %>%
        dplyr::arrange(Sample, source_target, dplyr::desc(score), .by_group = TRUE)

    sca <- obj_liana %>%
        dplyr::select(source_target, complex_interaction, Sample, sca.LRscore) %>%
        dplyr::mutate(method = "SCA (LIANA)") %>%
        dplyr::rename(score = sca.LRscore) %>%
        dplyr::group_by(Sample, source_target, ) %>%
        dplyr::arrange(Sample, source_target, dplyr::desc(score), .by_group = TRUE)

    cytotalk <- obj_liana %>%
        dplyr::select(source_target, complex_interaction, Sample, cytotalk.crosstalk_score) %>%
        dplyr::mutate(method = "Cytotalk (LIANA)") %>%
        dplyr::rename(score = cytotalk.crosstalk_score) %>%
        dplyr::group_by(Sample, source_target, ) %>%
        dplyr::arrange(Sample, source_target, dplyr::desc(score), .by_group = TRUE)

    # Sorting by p-values
    obj_cellchat <- obj_cellchat %>%
        dplyr::group_by(Sample, source_target, ) %>%
        dplyr::arrange(Sample, source_target, pval, .by_group = TRUE)

    obj_cell2cell <- obj_cell2cell %>%
        dplyr::group_by(Sample, source_target, ) %>%
        dplyr::arrange(Sample, source_target, pval, .by_group = TRUE)

    obj_cpdb <- obj_cpdb %>%
        dplyr::group_by(Sample, source_target, ) %>%
        dplyr::arrange(Sample, source_target, pval, .by_group = TRUE)

    # Grab all source-target pairs
    source_target_pairs <- unique(
        c(
            obj_cellchat %>% dplyr::pull(source_target) %>% unique(),
            obj_liana %>% dplyr::pull(source_target) %>% unique(),
            obj_cell2cell %>% dplyr::pull(source_target) %>% unique(),
            obj_cpdb %>% dplyr::pull(source_target) %>% unique()
        )
    )

    # Robust Rank Aggregation across all methods
    aggregated_ranks <- lapply(
        source_target_pairs,
        rank_interactions,
        connectome = connectome,
        sca = sca, cytotalk = cytotalk,
        natmi = natmi,
        logfc = logfc,
        obj_cellchat = obj_cellchat,
        obj_cell2cell = obj_cell2cell,
        obj_cpdb = obj_cpdb
    )

    interactions_df_aggregated <- do.call(rbind, aggregated_ranks) %>%
        dplyr::rename(complex_interaction = Name, pval = Score) %>%
        dplyr::mutate(Sample = obj_liana %>% dplyr::pull(Sample) %>% unique()) %>%
        tibble::remove_rownames() %>%
        # Adding individual p-values
        dplyr::left_join(obj_cellchat %>%
            dplyr::rename(cellchat = pval) %>%
            dplyr::select(Sample, source_target, complex_interaction, cellchat, CellChat_score)) %>%
        dplyr::left_join(obj_cell2cell %>%
            dplyr::rename(cell2cell = pval) %>%
            dplyr::select(Sample, source_target, complex_interaction, cell2cell)) %>%
        dplyr::left_join(obj_liana %>%
            dplyr::rename(liana = pval) %>%
            dplyr::select(Sample, source_target, complex_interaction, liana, LIANA_score)) %>%
        dplyr::left_join(obj_cpdb %>%
            dplyr::rename(cpdb = pval) %>%
            dplyr::select(Sample, source_target, complex_interaction, cpdb, CellPhoneDB_score))
    message("Save RRA interactions...")
    saveRDS(
        interactions_df_aggregated,
        glue::glue("{output_dir}/{sample_id}__interactions_agg_rank.rds")
    )
    message("Finished!")
}
